language: ruby

rvm:
  - 2.0.0

env:
  - DB=sqlite
  - DB=postgresql

# matrix:
#   allow_failures:
#     - rvm: 2.0.0

before_install:
  - git submodule update --init --recursive

script:
  script/ci
